<?php

namespace App\Services;

use App\Models\BillingInvoice;
use Illuminate\Support\Collection;

class InvoicePdfService
{
    public function render(BillingInvoice $invoice): string
    {
        $subscription = $invoice->subscription()->with('plan')->first();
        $tenant = tenant();

        $lines = Collection::make([
            $tenant?->name ?? 'N/A'.' Invoice',
            '',
            'Invoice Number: '.$invoice->invoice_number,
            'Company: '.($tenant?->name ?? 'N/A'),
            'Billing Email: '.($tenant?->billing_email ?? 'N/A'),
            'Status: '.strtoupper($invoice->status),
            'Issued At: '.optional($invoice->issued_at)->format('Y-m-d'),
            'Due At: '.optional($invoice->due_at)->format('Y-m-d'),
            'Paid At: '.(optional($invoice->paid_at)->format('Y-m-d') ?: 'Pending'),
            '',
            'Subscription Plan: '.($subscription?->plan?->name ?? 'N/A'),
            'Billing Period: '.strtoupper($subscription?->billing_period ?? 'N/A'),
            'Amount: '.$invoice->currency.' '.number_format((float) $invoice->amount, 2),
            '',
            'Generated by '.$tenant?->name ?? '',
        ]);

        $content = "BT\n/F1 12 Tf\n";
        $y = 780;

        foreach ($lines as $line) {
            $content .= sprintf("1 0 0 1 50 %d Tm (%s) Tj\n", $y, $this->escape($line));
            $y -= 22;
        }

        $content .= "ET";

        $objects = [];
        $objects[] = '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj';
        $objects[] = '2 0 obj << /Type /Pages /Count 1 /Kids [3 0 R] >> endobj';
        $objects[] = '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj';
        $objects[] = '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj';
        $objects[] = '5 0 obj << /Length '.strlen($content).' >> stream'."\n".$content."\n".'endstream endobj';

        $pdf = "%PDF-1.4\n";
        $offsets = [0];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object."\n";
        }

        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        foreach (array_slice($offsets, 1) as $offset) {
            $pdf .= sprintf('%010d 00000 n ', $offset)."\n";
        }

        $pdf .= "trailer << /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);
    }
}
